### ISSUE TITLE
project not work

### ISSUE THREAD

**Issue by deazure** [channaveer/hotel_management#2]
hello 
i download the project and follow the instruction :+1: 
Hotel Management Installation Steps

Note - Maker sure to enable "short_open_tag=On" in your 'php.ini' file.

Copy the unzipped project folder to www/htdocs location and change the project name to 'hotel'

OR

Change the your project base_url name in app/config.php folder to the following

$config['base_url'] = 'http://localhost/hotel_managment';

Create a database with name 'hotel' and Open 'Database' folder which is in project root folder and dump the 'hotel.sql' file to database using phpmyadmin or any other relavent tools.

OR

If you have given the name of the database other then 'hotel' then change the name of the database on app/database.php to the following

$db['default']['hostname'] = 'localhost'; $db['default']['username'] = 'root'; //DB username $db['default']['password'] = ''; //DB password $db['default']['database'] = 'hotel_managment'; //In case if your database name is 'hotel_managment'

Open browser with the the following url localhost/hotel

or

localhost/your_project_name
Now login with the following credentials
username - channaveer password - channaveer

 after i going to localhost/file_project but i don't work 

can you help me 
tanks

**Comment by channaveer** [comment]
Please check .htaccess file whether you have changed the name of the project
- Instead of 
  
    RewriteRule ^(.*)$ /hotel/index.php/$1 [L]
- You need to replace by
    RewriteRule ^(.*)$ /your_project_name/index.php/$1 [L]

**Comment by deazure** [comment]
thks
1. i change this ligne but nothing

RewriteRule ^(.*)$ /file_projet_name/index.php/$1 [L]
1. what is the nginx.conf

what it do ?

how i can do ?

**Comment by channaveer** [comment]
Please follow the following steps.
- Did you follow the instructions properly?
- If your using WAMP please try to enable "rewrite_module" under apache modules. 
- Even if your facing the same problem try to rename ".htaccess" file with other and check whether its working or not. If it works then you need to modify the name of the project in ".htaccess" and config folder of your app in codeigniter module.
- Even you must enable short codes in your php.ini file
- Even try to check in your **error.log** file it will show you what might be the issue.
- Use the following line in the following file
  
  www/project_folder/index.php
  
  In both the environment ie dev or prod condition add the following line and remove  "error_reporting(0);"
  
  ini_set('display_errors', 1);
