### ISSUE TITLE
Display Data

### ISSUE THREAD

**Issue by vinisaraiva** [channaveer/hotel_management#3]
Hello, I need a help please....
Studying the code, can register but can not show the data in rooms, room types, employes, etc
![erro](https://cloud.githubusercontent.com/assets/23156155/19840005/771c6866-9ecb-11e6-99c5-21715e0fbe30.jpg)

**Comment by channaveer** [comment]
Hi Vinisaraiva,
The PHP code which you have written to display is not correct, that's why the code is displayed in HTML page. Please find the image attached. 

If this doesn't work please provide me your mail id will send you code and database with some test data in it. Hope this helps to solve your problem.
![hotel_error](https://cloud.githubusercontent.com/assets/7845383/19920745/a3282c9c-a100-11e6-9dce-76bdefadd609.jpg)

**Comment by Adobanyi** [comment]
I have the same problem, i do not understand what u mean by php tags, that code is already in php tags, why is it wrong, you wrote the code right?

**Comment by channaveer** [comment]
Hey hi Adobanyi. I meant PHP SHORT TAGS (<? ?>)

No I didn't write the code I cloned it from else where. There was not database support in the project where I cloned. So thought that it will help someone else. And made this repo.

**Comment by Adobanyi** [comment]
OK please, is there a way i can get a working copy, i do have some knowledge in PHP but i havnt been able to make it work, thanks

**Comment by Adobanyi** [comment]
Or can you please email me one with some test data in it, especially the reservation, how can i make that work. thanks

**Comment by channaveer** [comment]
Hey hi Adobanyi if your using wamp server then use the following method to enable PHP Short Tags
http://stackoverflow.com/questions/7306997/php-wamp-server
http://stackoverflow.com/questions/12579448/php-short-open-tag-on-not-working
http://stackoverflow.com/questions/2185320/how-to-enable-php-short-tags
http://stackoverflow.com/questions/4645898/how-to-set-short-tag-in-php

NOTE - Don't forget to restart the WAMP server. Cheers!

![wamp server](https://cloud.githubusercontent.com/assets/7845383/26295853/af6ffec6-3ee9-11e7-85ae-724cefe9e546.png)

**Comment by Adobanyi** [comment]
I have open short tags, but my booking is still not working, I jst want to
know if you have a working version for booking?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Mon, May 22, 2017 at 7:55 AM, Channaveer Hakari <notifications@github.com

**Comment by artlantis** [comment]
@Adobanyi @vinisaraiva here is the original app link: https://github.com/tugbadogan/hotelmanagement

**Comment by channaveer** [comment]
@Adobanyi  Yep the above link posted by @artlantis  is the original one. I have tweaked few things that's it. I don't have a working copy for booking. Thanks.

**Comment by ahmj1** [comment]
I am trying to run the project using wamp, followed exactly all the steps as explained, however I am getting the following error ( in the log file) after logging in as channaveer

ERROR - 2017-05-26 07:54:32 --> Severity: Notice  --> Undefined variable: error C:\wamp64\www\hotel\application\views\login.php 11

and then screen goes blank with the address bar showing http://localhost/hotel/welcome/index

line 11 from C:\wamp64\www\hotel\application\views\login.php 11 is:
<?		
if(@$error) {
	?>
I have not changed anything in the code. Help is appreciated, as this seems to be and interesting project.

**Comment by channaveer** [comment]
Hi @ahmj1  can you please send the screen shot of the error your facing. So that I can help you better

**Comment by ahmj1** [comment]
Here are the relevant screenshots.
After logging in, I get a blank screen as shown.

![2017-05-27](https://cloud.githubusercontent.com/assets/28988639/26518275/4496c138-42be-11e7-8ab4-b37455df64a0.png)
![2017-05-27 1](https://cloud.githubusercontent.com/assets/28988639/26518276/44bebd6e-42be-11e7-86d2-6832c722c20c.png)
![2017-05-27 2](https://cloud.githubusercontent.com/assets/28988639/26518277/44dedad6-42be-11e7-92eb-d88420cfc1c6.png)

**Comment by channaveer** [comment]
Hi @ahmj1  can I have your email id please so that I can send you my local working copy project. The one who wrote the code have use suppressor (ie @ in the beginning).
