### ISSUE TITLE
cannot open the page

### ISSUE THREAD

**Issue by MarcoChong** [channaveer/hotel_management#4]
![1](https://cloud.githubusercontent.com/assets/25070075/25939402/525aa52e-3665-11e7-93c2-fda91c8852ee.png)
 already set up the pip.ini .

**Comment by lazehang** [comment]
# check your .htaccess file and replace
RewriteRule ^(.*)$ /hotel/index.php/$1 [L]
## with
RewriteRule ^(.*)$ /hotel_management/index.php/$1 [L]
